### ISSUE TITLE
Goreleaser to provide automated homebrew and Scoop install packages for developer installs

### ISSUE THREAD

**Issue by sheldonhull** [restechnica/semverbot#15]
If you leverage goreleaser for the build, github release, homebrew update, and scoop packages can all be done with minimal effort as it's built into that tool. 

I suggest Scoop since it's similar to Homebrew, but focused on Windows dev tools. 
Would be a nice way to make it more accessible to the different development platforms. 

If you want a goreleaser config PR to help jump start just let me know. Be more than willing to help as I get some time.

**Comment by shiouen** [comment]
Hi @sheldonhull 

That's a great suggestion. If you can find some time, I would really appreciate that! Looking forward to seeing your PR.

p.s. I might have to prep the repo somewhat to open it up to contribution by people outside 'restechnica', let me know if you need anything

**Comment by sheldonhull** [comment]
I tried out this initially, and was hoping to run `go install github.com/restechnica/semverbot@latest` but for some reason it didn't seem to register as a tool in bin.

If that's a supported install mechanism then that's great as well, as would work on all platforms without more packaging complexity.

**Comment by shiouen** [comment]
Hey @sheldonhull I totally missed this comment - I think my github notifications aren't set up right. I'll try the go install for myself too and update you.

**Comment by shiouen** [comment]
@sheldonhull I just tried the same command it works without issues, the only thing I didn't expect is that the name of the binary is `semverbot` instead of `sbot`. With homebrew I don't use `go build` instead of `go install`, would that work with what you're trying to achieve?

**Comment by sheldonhull** [comment]
The binary being different threw me for a loop. Maybe add that to the install directions on readme and call it a day :-) Was expecting binary to be same name as the directions. Thanks for the update!

**Comment by sheldonhull** [comment]
And contributors are allowed without issue if it's from a forked repo I'm pretty sure. 
Been swamped but if I get a chance I'll try and put an example together.
