### ISSUE TITLE
Mode `git-commit` doesn't appear to support parsing multi-line commit messages

### ISSUE THREAD

**Issue by mcblair** [restechnica/semverbot#45]
Repo steps:
1. Make commit with the following commit message:
```
My work.
[release]
```
2. Run `sbot predict version`, output:
```
% sbot predict version
Error: failed to detect mode from git commit message "My work.
" with delimiters "[]"
Usage:
  sbot predict version [flags]

Flags:
  -h, --help          help for version
  -m, --mode string   sbot mode (default "auto")

Global Flags:
  -c, --config string   configures which config file to use (default ".semverbot.toml")
```

Success case:
1. Make commit with the following commit message: `My work. [release]`.
2. Run `sbot predict version`, output: `1.0.0`

**Comment by shiouen** [comment]
Hi @mcblair 

I am looking into it, I just tried to reproduce this issue and also get an error with that commit message, but there is a subtle difference in output. I am on unix, which OS are you on?

Could you run the following and post its output? `git --no-pager show -s --format=%s`

**Comment by ToneVDB** [comment]
On a mac M1 , when running the below in a shell:
```sh
➜  testrepo git:(master) ✗ git commit -m 'my work
quote> [release]'
[master 86afadb] my work [release]
 1 file changed, 3 insertions(+)
➜  testrepo git:(master) sbot predict version
1.0.0
```
It seems to work.
@mcblair How did you make the newline?
Are you using git from the commandline?

**Comment by shiouen** [comment]
closing stale issue

**Comment by shiouen** [comment]
closing stale issue
